package com.sharon.couponsystem.beans;

import java.sql.Timestamp;

import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.bind.annotation.XmlAccessType;

import com.sharon.couponsystem.enums.CouponType;

//we are creating annotations so that jersey will translate JSON into
//a java bean "coupon". note that in this approach we need to set
//the annotation @XmlElement in each of the variables
//if we will not set the annotation in one of the variables jersey will
//not set the variable into the java object
@XmlAccessorType(XmlAccessType.NONE) 
@XmlRootElement(name = "coupon") 
public class Coupon {

	@XmlElement(name = "id", required = false) 
	private long id;

	@XmlElement(name = "title", required = true) 
	private String title;

	// in these 2 annotations we are forcing jersey to translate the JSON
	// using the Adapter we have created
	@XmlElement(name = "startDate", required = true) 
	@XmlJavaTypeAdapter(com.sharon.couponsystem.utils.TimestampAdapter.class)
	private Timestamp startDate;

	// in these 2 annotations we are forcing jersey to translate the JSON
	// using the Adapter we have created
	@XmlElement(name = "endDate", required = true) 
	@XmlJavaTypeAdapter(com.sharon.couponsystem.utils.TimestampAdapter.class)
	private Timestamp endDate;

	@XmlElement(name = "amount", required = true) 
	private int amount;

	@XmlElement(name = "type", required = true) 
	private CouponType type;

	@XmlElement(name = "message", required = true) 
	private String message;

	@XmlElement(name = "price", required = true) 
	private double price;

	@XmlElement(name = "image", required = true) 
	private String image;

	public Coupon(){
		
	}
	
	//This Ctor is used for coupon "reconstruction" after extraction from the sql database
	public Coupon(long id, String title, Timestamp startDate, Timestamp endDate, int amount, CouponType type, String message,
			double price, String image) {
		this(title, startDate, endDate, amount, type, message, price, image);
		this.id = id;
	}

	//This Ctor is used when creating our coupon ourselves, the id is self generated by the DB
	public Coupon(String title, Timestamp startDate, Timestamp endDate, int amount, CouponType type, String message,
			double price, String image) {
		this.title = title;
		this.startDate = startDate;
		this.endDate = endDate;
		this.amount = amount;
		this.type = type;
		this.message = message;
		this.price = price;
		this.image = image;
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Timestamp getStartDate() {
		return startDate;
	}

	public void setStartDate(Timestamp startDate) {
		this.startDate = startDate;
	}

	public Timestamp getEndDate() {
		return endDate;
	}

	public void setEndDate(Timestamp endDate) {
		this.endDate = endDate;
	}

	public int getAmount() {
		return amount;
	}

	public void setAmount(int amount) {
		this.amount = amount;
	}

	public CouponType getType() {
		return type;
	}

	public void setType(CouponType type) {
		this.type = type;
	}

	public String getMessage() {
		return message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public double getPrice() {
		return price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public String getImage() {
		return image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Override
	public String toString() {
		return "Coupon [id=" + id + ", title=" + title + ", startDate=" + startDate + ", endDate=" + endDate
				+ ", amount=" + amount + ", type=" + type + ", message=" + message + ", price=" + price + ", image="
				+ image + "]";
	}

}
